### PR TITLE
Add functions to replicate save, load from base.

### PR DESCRIPTION
**Pull request by superchordate**
Addresses issue #33 Wrapper to replace base save and load operations. 
* I chose names reminiscent of save, load from base. 
* @traversc I'm not sure how you are testing and I'm getting a DLL error when I try to run Roxygen so feel free to run those, or let me know your preferred method.

### CODE REVIEW

**Comment by hadley** [comment]
Is there a reason this added the R 3.5 requirement back in?

**Comment by traversc** [comment]
Hi @hadley I added 3.5 because I wanted ALT-REP support, and I felt it was too cumbersome to support and test for R < 3.5.

**Comment by traversc** [comment]
@hadley Do you think there is value in supporting R < 3.5? Would appreciate your insight or advice.

**Comment by hadley** [comment]
We've committed to supporting R-devel, R-release, and the last four versions for the tidyverse (which I think is good idea since RStudio commercial customers tend to be on older versions of R, and we have the resources to do it). It's harder to say for individuals — the requirement for R 3.5 means that we can't use qs in important tidyverse packages, but the only place where we really need it is multidplyr, and I'm happy for that to require 3.5.  That said, if it's relatively easy to keep 3.5 support, we'd definitely appreciate it.

**Pull request merged**
