### PR TITLE
Further overhaul roxygen2 documentation

### PR DESCRIPTION
**Pull request by salim-b**
Further overhaul roxygen2 documentation:

- add file `R/qs-package.R` for [package-level documentation](https://roxygen2.r-lib.org/articles/rd.html#packages)
- let roxygen2 [autogenerate the `NAMESPACE` file](https://roxygen2.r-lib.org/articles/namespace.html) and add missing `@export` tags wherever needed
- remove `@usage` blocks for native R functions, so they are autogenerated by roxygen2 \
NOTE that Rcpp code could also be [documented directly using roxygen2](https://roxygen2.r-lib.org/articles/roxygen2.html#rcpp), so we could even avoid the remaining `@usage` blocks, too (and use `@inheritParams` there instead of the `@eval`-tag solution)
- arrange roxygen2 tags in "standard" order ([no need to explicitly name `@details` tag that way](https://roxygen2.r-lib.org/articles/rd.html#the-description-block))
- tweak documentation at various places

Plus

- add RStudio project config file `qs.Rproj`
- remove executable bits from source file permissions
- harmonize R file extensions (`ascii_encoding.R`)
- remove surplus trailing newlines

### CODE REVIEW

**Comment by traversc** [comment]
> NOTE that Rcpp code could also be documented directly using roxygen2, so we could even avoid the remaining @usage blocks, too (and use @inheritParams there instead of the @eval-tag solution)

Would like to avoid adding roxygen2 to C++ files for now, as it's already pretty crowded and long. At some point I think a re-factor is warranted, breaking down functions into individual C++ files. 

> add RStudio project config file qs.Rproj

Can you explain the value of adding a Rproj file? 

> NAMESPACE file

It looks like some of the imports got dropped, causing the tests to fail? 

I'm going to merge for now so we have one base to work from.

**Comment by salim-b** [comment]
> Would like to avoid adding roxygen2 to C++ files for now, as it's already pretty crowded and long. At some point I think a re-factor is warranted, breaking down functions into individual C++ files.

Sure, I understand. Just wanted to point out the possibility and upsides of documenting directly in Rcpp files.

> Can you explain the value of adding a Rproj file?

It harmonizes configuration for all RStudio users contributing to this project (maybe only me currently 😅). An example is `LineEndingConversion: Posix` which is especially relevant for Windows users, i.e. can be very annoying if not set and some Windows user suddenly (and ignorantly) converts a file to CRLF line endings in a PR.

Rproj files have kinda the same purpose as [`.editorconfig`](https://editorconfig.org/) files, but are less powerful and RStudio-only. There's a [feature request for adding `.editorconfig`-support to RStudio](https://github.com/rstudio/rstudio/issues/1711) which some RStudio devs also would like to have implemented, but this didn't happen so far.

> It looks like some of the imports got dropped, causing the tests to fail?

Ah, damn. I noticed you had specified the imports

```r
import(RApiSerialize)
import(stringfish)
importFrom(Rcpp,sourceCpp)
```

in the NAMESPACE file but I (wrongly?) believed that they aren't actually needed since in all relevant places (tests, vignettes) you would either explicitly specify to load (`library(...)`) these packages before using them or use explicit namespace identifiers (like `Rcpp::...`).

If you think these package-wide imports are still required, you can simply add them to `R/qs-package.R` for example (in fact, any roxygenized R file will work):

```r
#' @import(RApiSerialize)
#' @import(stringfish)
#' @importFrom(Rcpp,sourceCpp)
```

**Comment by traversc** [comment]
The imports are necessary for properly linking C++ source files from other packages. I don't fully recall how that works, might be possible to put it in the DESCRIPTION file.

**Comment by salim-b** [comment]
> At some point I think a re-factor is warranted, breaking down functions into individual C++ files.

If you plan on a re-factor, might be worth considering the modern Rcpp alternative [cpp11](https://cpp11.r-lib.org/articles/motivations.html)... (I got no clue how relevant the differences between the two packages would actually be to qs)

**Comment by traversc** [comment]
The main difference between Rcpp and cpp11 is that they provide different wrappers to R's C API. But all of the critical code in the package is working on the C API directly, so there wouldn't be a benefit to switching to cpp11.

**Pull request merged**
